# Generated by Django 5.1.2 on 2024-10-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('expires', models.DateField(auto_now_add=True, verbose_name='expiry date')),
                ('name', models.CharField(max_length=100, verbose_name='associated name')),
                ('cvv', models.IntegerField(verbose_name='security code')),
            ],
        ),
    ]
