# Generated by Django 5.1.2 on 2024-10-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_validation_app', '0002_alter_card_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=23, verbose_name='number'),
        ),
    ]
